const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('gitAPI', {
  startRepoWatch: (repoPath) => ipcRenderer.invoke('repo-watch-start', repoPath),
  stopRepoWatch: () => ipcRenderer.invoke('repo-watch-stop'),
  onRepoFilesChanged: (callback) => {
    const handler = (_event, repoPath) => callback(repoPath)
    ipcRenderer.on('repo-files-changed', handler)
    return () => ipcRenderer.removeListener('repo-files-changed', handler)
  },
  selectDirectory: () => ipcRenderer.invoke('select-directory'),
  checkRepository: (repoPath) => ipcRenderer.invoke('git-check-repo', repoPath),
  initRepository: (repoPath) => ipcRenderer.invoke('git-init', repoPath),
  getStatus: (repoPath) => ipcRenderer.invoke('git-status', repoPath),
  getLog: (repoPath, maxCount) => ipcRenderer.invoke('git-log', repoPath, maxCount),
  getLogForBranch: (repoPath, branchName, maxCount) =>
    ipcRenderer.invoke('git-log-branch', repoPath, branchName, maxCount),
  searchLog: (repoPath, keyword, maxCount) => ipcRenderer.invoke('git-log-search', repoPath, keyword, maxCount),
  addFiles: (repoPath, files) => ipcRenderer.invoke('git-add', repoPath, files),
  discardFiles: (repoPath, filePaths) => ipcRenderer.invoke('git-discard-files', repoPath, filePaths),
  ignorePath: (repoPath, filePath, mode = 'path') =>
    ipcRenderer.invoke('git-ignore-path', repoPath, filePath, mode),
  getIgnoreList: (repoPath) => ipcRenderer.invoke('git-ignore-list', repoPath),
  removeIgnoreEntry: (repoPath, entry) => ipcRenderer.invoke('git-ignore-remove', repoPath, entry),
  commit: (repoPath, message) => ipcRenderer.invoke('git-commit', repoPath, message),
  push: (repoPath, force = false, options) => ipcRenderer.invoke('git-push', repoPath, force, options),
  getRemotePushInfo: (repoPath) => ipcRenderer.invoke('git-remote-push-info', repoPath),
  addRemote: (repoPath, remoteName, url) => ipcRenderer.invoke('git-remote-add', repoPath, remoteName, url),
  removeRemote: (repoPath, remoteName) => ipcRenderer.invoke('git-remote-remove', repoPath, remoteName),
  pull: (repoPath) => ipcRenderer.invoke('git-pull', repoPath),
  fetch: (repoPath) => ipcRenderer.invoke('git-fetch', repoPath),
  resetFile: (repoPath, filePath) => ipcRenderer.invoke('git-reset-file', repoPath, filePath),
  resetStaged: (repoPath) => ipcRenderer.invoke('git-reset-staged', repoPath),
  addAll: (repoPath) => ipcRenderer.invoke('git-add-all', repoPath),
  showCommit: (repoPath, hash) => ipcRenderer.invoke('git-show', repoPath, hash),
  getCommitFiles: (repoPath, hash) => ipcRenderer.invoke('git-commit-files', repoPath, hash),
  getCommitFileDiff: (repoPath, hash, filePath) => ipcRenderer.invoke('git-commit-file-diff', repoPath, hash, filePath),
  getCommitFileSnapshot: (repoPath, hash, filePath, side) =>
    ipcRenderer.invoke('git-commit-file-snapshot', repoPath, hash, filePath, side),
  resetToCommit: (repoPath, hash, mode) => ipcRenderer.invoke('git-reset-to-commit', repoPath, hash, mode),
  diffCommits: (repoPath, hashA, hashB) => ipcRenderer.invoke('git-diff-commits', repoPath, hashA, hashB),
  getConflictVersions: (repoPath, filePath) => ipcRenderer.invoke('git-conflict-versions', repoPath, filePath),
  getBranches: (repoPath) => ipcRenderer.invoke('git-branches', repoPath),
  getOperationState: (repoPath) => ipcRenderer.invoke('git-operation-state', repoPath),
  rebaseContinue: (repoPath) => ipcRenderer.invoke('git-rebase-continue', repoPath),
  rebaseSkip: (repoPath) => ipcRenderer.invoke('git-rebase-skip', repoPath),
  cherryPickContinue: (repoPath) => ipcRenderer.invoke('git-cherry-pick-continue', repoPath),
  cherryPickAbort: (repoPath) => ipcRenderer.invoke('git-cherry-pick-abort', repoPath),
  cherryPickSkip: (repoPath) => ipcRenderer.invoke('git-cherry-pick-skip', repoPath),
  mergeContinue: (repoPath) => ipcRenderer.invoke('git-merge-continue', repoPath),
  finishSquashMerge: (repoPath, sourceBranch) => ipcRenderer.invoke('git-finish-squash-merge', repoPath, sourceBranch),
  mergeAbort: (repoPath) => ipcRenderer.invoke('git-merge-abort', repoPath),
  markResolved: (repoPath, filePath) => ipcRenderer.invoke('git-mark-resolved', repoPath, filePath),
  checkoutRemote: (repoPath, remoteBranch) => ipcRenderer.invoke('git-checkout-remote', repoPath, remoteBranch),
  checkout: (repoPath, branch) => ipcRenderer.invoke('git-checkout', repoPath, branch),
  getDiff: (repoPath, filePath) => ipcRenderer.invoke('git-diff', repoPath, filePath),
  getDiffCached: (repoPath, filePath) => ipcRenderer.invoke('git-diff-cached', repoPath, filePath),
  readWorkingFile: (repoPath, filePath) => ipcRenderer.invoke('git-read-working-file', repoPath, filePath),
  getHeadFileSnapshot: (repoPath, filePath) => ipcRenderer.invoke('git-head-file-snapshot', repoPath, filePath),
  getIndexFileSnapshot: (repoPath, filePath) => ipcRenderer.invoke('git-index-file-snapshot', repoPath, filePath),
  openPath: (fullPath) => ipcRenderer.invoke('open-path', fullPath),
  openRepoFile: (repoPath, filePath) => ipcRenderer.invoke('git-open-repo-file', repoPath, filePath),
  createBranch: (repoPath, branchName) => ipcRenderer.invoke('git-create-branch', repoPath, branchName),
  mergeBranch: (repoPath, branchName, mode) => ipcRenderer.invoke('git-merge', repoPath, branchName, mode),
  deleteBranch: (repoPath, branchName, force) => ipcRenderer.invoke('git-delete-branch', repoPath, branchName, force),
  renameBranch: (repoPath, oldName, newName) => ipcRenderer.invoke('git-rename-branch', repoPath, oldName, newName),
  rebase: (repoPath, ontoBranch) => ipcRenderer.invoke('git-rebase', repoPath, ontoBranch),
  rebaseAbort: (repoPath) => ipcRenderer.invoke('git-rebase-abort', repoPath),
  getStashList: (repoPath) => ipcRenderer.invoke('git-stash-list', repoPath),
  stashSave: (repoPath, message) => ipcRenderer.invoke('git-stash-save', repoPath, message),
  stashApply: (repoPath, index) => ipcRenderer.invoke('git-stash-apply', repoPath, index),
  stashDrop: (repoPath, index) => ipcRenderer.invoke('git-stash-drop', repoPath, index),
  getTags: (repoPath) => ipcRenderer.invoke('git-tags', repoPath),
  createTag: (repoPath, tagName, message) => ipcRenderer.invoke('git-tag-create', repoPath, tagName, message),
  deleteTag: (repoPath, tagName) => ipcRenderer.invoke('git-tag-delete', repoPath, tagName),
  pushTags: (repoPath) => ipcRenderer.invoke('git-push-tags', repoPath),
  cherryPick: (repoPath, hash) => ipcRenderer.invoke('git-cherry-pick', repoPath, hash),
  clone: (url, parentDir) => ipcRenderer.invoke('git-clone', url, parentDir),
  getConfig: (repoPath, scope) => ipcRenderer.invoke('git-config-get', repoPath, scope),
  setConfig: (repoPath, name, email, scope) => ipcRenderer.invoke('git-config-set', repoPath, name, email, scope),
  getSubmodules: (repoPath) => ipcRenderer.invoke('git-submodules', repoPath),
  updateSubmodules: (repoPath, path) => ipcRenderer.invoke('git-submodule-update', repoPath, path)
})
